# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and test SDK

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
        AAD_APP_CLIENT_ID: ${{ secrets.AAD_APP_CLIENT_ID }}
        AAD_APP_CLIENT_SECRET: ${{ secrets.AAD_APP_CLIENT_SECRET }}
        AAD_APP_CERT: ${{ secrets.AAD_APP_CERT }}
        AAD_APP_CERT_SECRET: ${{ secrets.AAD_APP_CERT_SECRET }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file sdk/pom.xml
    - name: Create maven package
      run: mvn clean compile assembly:single --file sdk/pom.xml

      #todo: write workflow to push the project to be signed...
